app = 'config-8iywwg'
primary_region = 'fra'

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 8443
  protocol = "tcp"
  [[services.ports]]
    port = 8443
    handlers = ["tls"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
